# Generated by Django 2.1.7 on 2019-02-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Adesivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_de_venda', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Filme_bopp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('micragem', models.DecimalField(decimal_places=0, max_digits=2)),
                ('gramatura', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rendimento', models.DecimalField(decimal_places=1, max_digits=3)),
                ('valor_de_venda', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento_adesivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateTimeField()),
                ('servico', models.CharField(max_length=400)),
                ('comp', models.DecimalField(decimal_places=0, max_digits=3)),
                ('larg', models.DecimalField(decimal_places=0, max_digits=3)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=7)),
                ('acabamento', models.ForeignKey(on_delete='cascade', to='moduloof.Acabamento')),
                ('cliente', models.ForeignKey(on_delete='cascade', to='moduloof.Cliente')),
                ('material', models.ForeignKey(on_delete='cascade', to='moduloof.Adesivo')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento_filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateTimeField()),
                ('servico', models.CharField(max_length=400)),
                ('comp', models.DecimalField(decimal_places=0, max_digits=3)),
                ('larg', models.DecimalField(decimal_places=0, max_digits=3)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=7)),
                ('cliente', models.ForeignKey(on_delete='cascade', to='moduloof.Cliente')),
                ('material', models.ForeignKey(on_delete='cascade', to='moduloof.Filme_bopp')),
            ],
        ),
        migrations.CreateModel(
            name='Tpadesivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tpfilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='filme_bopp',
            name='tipo',
            field=models.ForeignKey(on_delete='cascade', to='moduloof.Tpfilme'),
        ),
        migrations.AddField(
            model_name='adesivo',
            name='tipo',
            field=models.ForeignKey(on_delete='cascade', to='moduloof.Tpadesivo'),
        ),
    ]
