# Generated by Django 2.1.5 on 2019-03-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acabamento',
            name='incremento',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=3),
            preserve_default=False,
        ),
    ]
