# Generated by Django 2.1.5 on 2019-03-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloof', '0002_acabamento_incremento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento_filme',
            name='acabamento',
            field=models.ForeignKey(default='', on_delete='cascade', to='moduloof.Acabamento'),
            preserve_default=False,
        ),
    ]
