# Generated by Django 2.1.5 on 2019-03-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloof', '0006_auto_20190319_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento_filme',
            old_name='acabamento',
            new_name='acabamentof',
        ),
    ]
