# Generated by Django 2.1.5 on 2019-03-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloof', '0007_auto_20190319_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento_filme',
            name='acabamentof',
        ),
    ]
