# Generated by Django 2.1.5 on 2019-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloof', '0008_remove_orcamento_filme_acabamentof'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento_filme',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='moduloof.Acabamento'),
        ),
    ]
